apiVersion: v1
kind: Service
metadata:
  name: cloud-billing-app-service
spec:
  type: NodePort
  selector:
    app: cloud-billing-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080